server:
  port: 8089

spring:
  kafka:
#    producer:
#      bootstrap-servers: "localhost:9092"
#      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
#      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      
      
    consumer:
      bootstrap-servers: "localhost:9092"
      group-id: "spring-boot-kafka-consumer"
      value-deserializer: "org.springframework.kafka.support.serializer.ErrorHandlingDeserializer"
      properties:
        spring:
          json:
            trusted:
              packages: "com.training.model"
          deserializer:
            value:
              delegate:
                class :   "org.springframework.kafka.support.serializer.JsonDeserializer"  
      
#              


  
  #spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
  #spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer